seed: 42

n_epochs: 10
batch_size: 256

train_ratio: 0.99

max_len: 22
model_name: "ALINEAR/albert-japanese-v2"

use_pickle: true
make_pickle: true

preprocess:
  min_size: 2
  max_size: 22
  num_use_uttr: 2

optimizer:
  lr: 0.001

model:
  vocab_size: 32000
  n_layers: 3
  n_head: 8
  channel: 768
  dropout: 0.1
